In [1]:
%matplotlib widget
import sklearn 
from sklearn import datasets 
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris() #import data
df = pd.DataFrame(iris.data)
#print(iris.DESCR)

In [3]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'] #name columns

In [4]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
df['class'] = iris['target'] #add class column

In [6]:
#make a little dict so I can easily label plots later
name_class_dict = {'Setosa':0, 'Versicolor':1, 'Virginica':2}

In [7]:
print(df)

     sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]


In [8]:
#need to shuffle this
df = shuffle(df, random_state=69)
df.reset_index(inplace=True, drop=True) 

In [9]:
df #check that it worked as expected

sepal_length  sepal_width  petal_length  petal_width  class
0             5.0          3.6           1.4          0.2      0
1             6.6          2.9           4.6          1.3      1
2             5.4          3.4           1.7          0.2      0
3             5.8          2.8           5.1          2.4      2
4             5.4          3.4           1.5          0.4      0
..            ...          ...           ...          ...    ...
145           4.6          3.6           1.0          0.2      0
146           5.0          3.3           1.4          0.2      0
147           5.5          2.6           4.4          1.2      1
148           7.3          2.9           6.3          1.8      2
149           6.5          2.8           4.6          1.5      1

[150 rows x 5 columns]

In [10]:
X_train, y_train = df.drop('class', axis=1)[:-30].to_numpy(), df['class'][:-30].to_numpy() #training set

In [11]:
X_test, y_test = df.drop('class', axis=1)[-30:].to_numpy(), df['class'][-30:].to_numpy() #test set

In [12]:
X_test.T

array([[5.9, 6.3, 5.1, 5.8, 6.7, 5. , 5. , 5.1, 5.1, 6. , 6.5, 5.6, 5.1,
        4.7, 4.8, 5.5, 4.6, 5.5, 6.6, 4.9, 6.7, 5.6, 5.7, 4.4, 4.9, 4.6,
        5. , 5.5, 7.3, 6.5],
       [3.2, 2.5, 3.7, 4. , 3.1, 3.5, 3.2, 3.3, 3.8, 3. , 3. , 2.8, 3.4,
        3.2, 3.4, 2.4, 3.1, 2.3, 3. , 2.5, 3.1, 3. , 2.9, 3. , 3.1, 3.6,
        3.3, 2.6, 2.9, 2.8],
       [4.8, 5. , 1.5, 1.2, 4.7, 1.6, 1.2, 1.7, 1.9, 4.8, 5.2, 4.9, 1.5,
        1.3, 1.9, 3.8, 1.5, 4. , 4.4, 4.5, 5.6, 4.1, 4.2, 1.3, 1.5, 1. ,
        1.4, 4.4, 6.3, 4.6],
       [1.8, 1.9, 0.4, 0.2, 1.5, 0.6, 0.2, 0.5, 0.4, 1.8, 2. , 2. , 0.2,
        0.2, 0.2, 1.1, 0.2, 1.3, 1.4, 1.7, 2.4, 1.3, 1.3, 0.2, 0.1, 0.2,
        0.2, 1.2, 1.8, 1.5]])

In [13]:
scaler = StandardScaler()  #scale training and test data
X_trainstd = scaler.fit_transform(X_train)
X_teststd = scaler.fit_transform(X_test)

In [14]:
#print(X_trainstd)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
logreg = LogisticRegression(multi_class='multinomial', tol=1e-5, C=5e-1, max_iter=1e3)

In [18]:
estimator=logreg.fit(X_trainstd, y_train)
#logreg.predict_proba(X_trainstd)

array([[9.76912335e-01, 2.30830118e-02, 4.65318806e-06],
       [1.42425636e-02, 7.76384573e-01, 2.09372863e-01],
       [9.16711924e-01, 8.32618871e-02, 2.61888544e-05],
       [7.56989830e-04, 8.39631687e-02, 9.15279841e-01],
       [9.11353774e-01, 8.86034288e-02, 4.27976686e-05],
       [9.91423962e-01, 8.57413204e-03, 1.90627892e-06],
       [4.73137508e-02, 8.39588656e-01, 1.13097593e-01],
       [1.33018667e-04, 6.69678977e-02, 9.32899084e-01],
       [8.53749628e-04, 2.68851761e-01, 7.30294489e-01],
       [9.92750662e-01, 7.24814431e-03, 1.19405006e-06],
       [2.09757021e-03, 5.99091954e-01, 3.98810475e-01],
       [1.75748162e-05, 2.96972921e-02, 9.70285133e-01],
       [9.30591322e-01, 6.93962650e-02, 1.24125692e-05],
       [8.41150400e-02, 6.14232246e-01, 3.01652714e-01],
       [3.74794215e-04, 8.01049426e-02, 9.19520263e-01],
       [2.36288278e-02, 8.22211745e-01, 1.54159427e-01],
       [5.05651298e-02, 9.19983373e-01, 2.94514968e-02],
       [2.90919327e-04, 6.55077

In [19]:
predicted_species = logreg.predict(X_teststd)

In [21]:
ifig = 1;plt.close(ifig);plt.figure()
plt.hist(predicted_species, alpha=1, color='gray') #predictions
plt.hist(y_test, alpha=0.5, color ='g') # ground truth
#light green high precision low recall -> not predicting incorrectly but missing values
#gray low precision high recall -> incorrectly predicting values 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([14.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  7.]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 <BarContainer object of 10 artists>)

In [22]:
import sklearn.metrics as skmetrics
confM = skmetrics.confusion_matrix(y_test,predicted_species)   #(y_true, y_predicted)

In [23]:
print(skmetrics.classification_report(y_test,predicted_species)) #f1 score = 2*((precision*recall)/(precision+recall))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.56      0.71         9
           2       0.64      1.00      0.78         7

    accuracy                           0.87        30
   macro avg       0.88      0.85      0.83        30
weighted avg       0.92      0.87      0.86        30



In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(estimator, X_train, y_train, cv=10, scoring = 'accuracy')

array([0.91666667, 1.        , 1.        , 1.        , 0.91666667,
       0.83333333, 1.        , 1.        , 0.91666667, 1.        ])

In [25]:
cross_val_score(estimator, X_train, y_train, cv=10, scoring = 'completeness_score') # 1-H(Ypred|YTrue)/H(Ytrue)
#see https://scikit-learn.org/stable/modules/model_evaluation.html#confusion-matrix or better
#https://esigma6.wordpress.com/2018/11/03/2-3-9-3-homogeneity-completeness-and-v-measure/ for more info

array([0.82604617, 1.        , 1.        , 1.        , 0.82604617,
       0.77155617, 1.        , 1.        , 0.81971597, 1.        ])

In [26]:
#skmetrics.homogeneity_completeness_v_measure(y_test, predicted_species)

(0.7724935564912162, 0.7983812880039207, 0.7852241096958964)

In [88]:
predicted_virginica_PL = X_test.T[2][predicted_species == name_class_dict['Virginica']]
predicted_virginica_PW = X_test.T[3][predicted_species == name_class_dict['Virginica']]

predicted_versicolor_PL = X_test.T[2][predicted_species == name_class_dict['Versicolor']]
predicted_versicolor_PW = X_test.T[3][predicted_species == name_class_dict['Versicolor']]


predicted_setosa_PL = X_test.T[2][predicted_species == name_class_dict['Setosa']]
predicted_setosa_PW = X_test.T[3][predicted_species == name_class_dict['Setosa']]

In [91]:
ifig = 2;plt.close(ifig);plt.figure(figsize=(8,6))

plt.scatter(df.petal_length[df['class'] == name_class_dict['Versicolor']] ,\
                            df.petal_width[df['class'] == name_class_dict['Versicolor']], c='green', marker='x', s=30,\
                            label='Versicolor') 

plt.scatter(df.petal_length[df['class'] == name_class_dict['Setosa']] ,\
                            df.petal_width[df['class'] == name_class_dict['Setosa']], c='m', marker='v', s=30,\
                            label='Setosa' )

plt.scatter(df.petal_length[df['class'] == name_class_dict['Virginica']] ,\
                            df.petal_width[df['class'] == name_class_dict['Virginica']], c='blueviolet', marker='*', s=30,\
                            label='Virginica') 

plt.scatter(predicted_virginica_PL,predicted_virginica_PW, c='blueviolet', marker='*', alpha=0.5,s=70) 
plt.scatter(predicted_versicolor_PL,predicted_versicolor_PW, c='green', marker='x', alpha=0.5,s=70) 
plt.scatter(predicted_setosa_PL,predicted_setosa_PW, c='m', marker='v', alpha=0.5, s=70) 



# create a mesh to plot in
h = .02  # step size in the mesh
x_min, x_max = df.petal_width.min() - 1, df.petal_width.max() + 1
y_min, y_max = df.petal_width.min() - 1, df.petal_length.max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))

# Plot the decision boundary. For that, we will assign a color to each
# point in the mesh [x_min, x_max]x[y_min, y_max].
print(np.c_[xx.ravel(), yy.ravel()])
Z = logreg.predict(np.c_[xx.ravel(), yy.ravel()])
# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure()
plt.contourf(xx, yy, Z, cmap=plt.cm.Paired)
plt.title("Decision surface of LogisticRegression (%s)" % multi_class)
plt.axis('tight')




#plt.plot(fake_petal_length,fake_petal_width)
plt.xlabel('petal length [cm]')
plt.ylabel('petal width [cm]')
plt.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[-0.9  -0.9 ]
 [-0.88 -0.9 ]
 [-0.86 -0.9 ]
 ...
 [ 3.44  7.88]
 [ 3.46  7.88]
 [ 3.48  7.88]]


ValueError: X has 2 features per sample; expecting 4

In [31]:
plt.scatter?

In [93]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression

# make 3-class dataset for classification
centers = [[-5, 0], [0, 1.5], [5, -1]]
X, y = make_blobs(n_samples=1000, centers=centers, random_state=40)
transformation = [[0.4, 0.2], [-0.4, 1.2]]
X = np.dot(X, transformation)
print(X,y)

for multi_class in ('multinomial', 'ovr'):
    clf = LogisticRegression(solver='sag', max_iter=100, random_state=42,
                             multi_class=multi_class).fit(X, y)

    # print the training scores
    print("training score : %.3f (%s)" % (clf.score(X, y), multi_class))

    # create a mesh to plot in
    h = .02  # step size in the mesh
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))

    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    print(np.c_[xx.ravel(), yy.ravel()])
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.figure()
    plt.contourf(xx, yy, Z, cmap=plt.cm.Paired)
    plt.title("Decision surface of LogisticRegression (%s)" % multi_class)
    plt.axis('tight')

    # Plot also the training points
    colors = "bry"
    for i, color in zip(clf.classes_, colors):
        idx = np.where(y == i)
        plt.scatter(X[idx, 0], X[idx, 1], c=color, cmap=plt.cm.Paired,
                    edgecolor='black', s=20)

    # Plot the three one-against-all classifiers
    xmin, xmax = plt.xlim()
    ymin, ymax = plt.ylim()
    coef = clf.coef_
    intercept = clf.intercept_

    def plot_hyperplane(c, color):
        def line(x0):
            return (-(x0 * coef[c, 0]) - intercept[c]) / coef[c, 1]
        plt.plot([xmin, xmax], [line(xmin), line(xmax)],
                 ls="--", color=color)

    for i, color in zip(clf.classes_, colors):
        plot_hyperplane(i, color)

plt.show()

[[-2.38519938  0.02641654]
 [-1.74830343 -1.4226907 ]
 [-2.45431681 -1.46071435]
 ...
 [-1.88691344 -1.67526794]
 [-0.96714666  4.62965124]
 [ 1.21127093  1.53964501]] [0 0 0 2 1 1 0 0 0 1 2 2 2 1 1 1 1 2 0 2 0 1 0 1 1 2 0 1 1 1 2 0 2 0 2 1 2
 2 0 0 1 0 0 0 1 2 0 0 0 2 0 0 0 1 1 0 1 2 0 1 2 1 2 2 0 1 1 0 1 0 1 2 1 1
 0 2 1 2 0 0 1 1 2 0 0 2 1 2 1 2 2 2 1 1 2 2 0 0 0 0 2 2 0 1 0 0 1 2 2 1 2
 1 0 1 1 2 0 2 1 1 0 1 2 2 2 0 0 1 0 2 0 2 2 1 2 1 0 1 2 2 2 2 2 1 1 1 1 2
 2 2 1 2 1 0 0 1 1 1 1 1 2 0 0 1 2 2 2 0 1 2 1 1 1 0 1 2 0 2 2 0 2 2 1 1 2
 0 1 0 0 2 1 1 0 1 0 1 1 0 0 0 1 2 2 1 0 0 1 0 1 1 2 0 0 0 1 2 1 2 1 2 0 2
 1 1 0 2 2 1 1 1 0 0 2 2 2 0 2 2 2 2 1 0 2 2 1 0 2 2 0 0 2 0 2 0 2 0 2 0 2
 2 0 1 1 1 1 2 1 1 1 2 1 2 0 1 2 0 0 2 2 2 0 2 0 0 1 1 1 2 1 0 2 0 0 0 2 2
 0 2 2 1 2 0 0 2 1 1 1 0 1 2 2 2 0 0 2 0 0 1 1 0 0 0 0 0 2 2 1 2 2 1 2 1 1
 2 0 0 1 0 0 2 2 1 1 0 1 0 0 2 2 2 1 1 2 0 0 2 2 2 1 1 0 1 2 1 1 2 1 2 0 0
 0 2 1 0 1 1 1 1 1 1 2 0 1 0 1 2 2 0 2 1 2 1 2 2 0 1 2 1 0 0 1 2 2 0 2 1 0
 2 2 1 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

training score : 0.976 (ovr)
[[-4.61124176 -5.88341015]
 [-4.59124176 -5.88341015]
 [-4.57124176 -5.88341015]
 ...
 [ 5.22875824  6.39658985]
 [ 5.24875824  6.39658985]
 [ 5.26875824  6.39658985]]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [90]:
X

array([[-2.38519938,  0.02641654],
       [-1.74830343, -1.4226907 ],
       [-2.45431681, -1.46071435],
       ...,
       [-1.88691344, -1.67526794],
       [-0.96714666,  4.62965124],
       [ 1.21127093,  1.53964501]])